"""
PROBLEM 2
https://projecteuler.net/problem=2
Even Fibonacci numbers
"""

# Track Execution time
import time

def solution():
    '''
    Solution 2
    ''' 
    start = time.time()

    # Variables
    total = 0
    fib = [1, 2]
    RANGE = 4_000_000

    #The problem doesn't ask to generate the fibonoacci list
    #but i did anyway so you could use the list in other ways if desired
    i = 2
    while (fib[i - 1] + fib[i - 2]) < RANGE:
        fib.append(fib[i - 1] + fib[i - 2])
        i += 1

    for y in fib:
        if y % 2 == 0:
            total += y

    # Print Execution Time
    end = time.time()
    print(f"Execution time: {(end-start):.3f}s")

    return total

def sol_text():
    '''
    Text of problem 2
    '''
    return '''Even Fibonacci Numbers:

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.'''
    